# Generated by Django 3.2.25 on 2025-02-14 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0001_initial'),
        ('inventory', '0002_inventory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='workshops.workshop'),
        ),
    ]
