# Generated by Django 3.2.25 on 2025-02-14 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0001_initial'),
        ('services', '0001_initial'),
        ('products', '0002_product_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='workshops.workshop'),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='service_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicerecord'),
        ),
    ]
